/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type StringList = string[];

export interface ARestic {
  repositories?:
    | {
        [k: string]: Repository;
      }
    | Repository[];
  backups?:
    | {
        [k: string]: Backup;
      }
    | Backup[];
  [k: string]: unknown;
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` ".+".
 */
export interface Repository {
  name?: string;
  backend?: "local" | "rest" | "sftp" | "s3" | "azure" | "gs" | "rclone";
  extends?: string;
  protocol?: "http" | "https";
  host?: string;
  username?: string;
  password?: string;
  passwordPath?: string;
  port?: number;
  path?: string;
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` ".+".
 */
export interface Backup {
  name?: string;
  repositories?: StringList;
  paths?: StringList;
  password?: string;
  passwordPath?: string;
  globalOptions?: GlobalOptionsCli;
  options?: BackupOptionsCli;
}
export interface GlobalOptionsCli {
  /**
   * file to load root certificates from (default: use system certificates)
   */
  cacert?: string;
  /**
   * set the cache directory. (default: use system default cache directory)
   */
  "cache-dir"?: string;
  /**
   * auto remove old cache directories
   */
  "cleanup-cache "?: boolean;
  /**
   * set output mode to JSON for commands that support it
   */
  json?: boolean;
  /**
   * key ID of key to try decrypting first (default: $RESTIC_KEY_HINT)
   */
  "key-hint"?: string;
  /**
   * limits downloads to a maximum rate in KiB/s. (default: unlimited)
   */
  "limit-download"?: number;
  /**
   * limits uploads to a maximum rate in KiB/s. (default: unlimited)
   */
  "limit-upload"?: number;
  /**
   * do not use a local cache
   */
  "no-cache"?: boolean;
  /**
   * do not lock the repo, this allows some operations on read-only repos
   */
  "no-lock"?: boolean;
  /**
   * set extended option (key=value, can be specified multiple times)
   */
  option?: string[];
  /**
   * specify a shell command to obtain a password (default: $RESTIC_PASSWORD_COMMAND)
   */
  "password-command"?: string;
  /**
   * read the repository password from a file (default: $RESTIC_PASSWORD_FILE)
   */
  "password-file"?: string;
  /**
   * do not output comprehensive progress report
   */
  quiet?: boolean;
  /**
   * repository to backup to or restore from (default: $RESTIC_REPOSITORY)
   */
  repo?: string;
  /**
   * path to a file containing PEM encoded TLS client certificate and private key
   */
  "tls-client-cert"?: string;
  /**
   * be verbose (specify --verbose multiple times or level n)
   */
  verbose?: number;
  [k: string]: unknown;
}
export interface BackupOptionsCli {
  /**
   * exclude a pattern (can be specified multiple times)
   */
  exclude?: string[];
  /**
   * excludes cache directories that are marked with a CACHEDIR.TAG file. See http://bford.info/cachedir/spec.html for the Cache Directory Tagging Standard
   */
  "exclude-caches"?: boolean;
  /**
   * read exclude patterns from a file (can be specified multiple times)
   */
  "exclude-file"?: string[];
  /**
   * takes filename[:header], exclude contents of directories containing filename (except filename itself) if header of that file is as provided (can be specified multiple times)
   */
  "exclude-if-present"?: string;
  /**
   * read the files to backup from file (can be combined with file args/can be specified multiple times)
   */
  "files-from"?: string;
  /**
   * force re-reading the target files/directories (overrides the "parent" flag)
   */
  force?: boolean;
  /**
   * set the hostname for the snapshot manually. To prevent an expensive rescan use the "parent" flag
   */
  host?: string;
  /**
   * same as --exclude but ignores the casing of filenames
   */
  iexclude?: string[];
  /**
   * ignore inode number changes when checking for modified files
   */
  "ignore-inode"?: boolean;
  /**
   * exclude other file systems
   */
  "one-file-system"?: boolean;
  /**
   * use this parent snapshot (default: last snapshot in the repo that has the same target files/directories)
   */
  parent?: string;
  /**
   * add a tag for the new snapshot (can be specified multiple times)
   */
  tag?: string[];
  /**
   * time of the backup (ex. '2012-11-01 22:08:41') (default: now)
   */
  time?: string;
  /**
   * store the atime for all files and directories
   */
  "with-atime"?: boolean;
  [k: string]: unknown;
}
